spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user_votacao
    password: p@$sw0rd1
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8081
   error:
     include-stacktrace: never

security:
  jwt:
    token:
      secret-key: p@$sw0rd1p@$sw0rd1
      expire-length: 300000
      
UsuarioController:
  signin: Autenticar usuário e retornar JWT token.
  refresh: Atualizar login do usuário gerando novo token.

PautaController:
  cadastrar: Cadastrar Pauta de votação.
  listar: Listar todas as Pautas de votação.

SessaoController:
  cadastrar: Cadastrar Sessão de votação.
  listar: Listar todas as Sessões de votação.
  totalizar: Totalizar votos da sessão.

VotoController:
  votar: Cadastrar VOTO.